---
title: "CompilingManualID_Dec2023"
output: html_document
date: "2023-12-13"
---

```{r}
library(data.table)
library(tidyverse)
library(beepr)
library(lubridate)
library(purrr)
library(janitor)
#renv::install("rstudio/renv")
library(renv)
library(stringr)
library(beepr)
library(kableExtra)
library(papeR)
library(skimr)
library(vtable)
library(ggdark)
library(RColorBrewer)
library(cowplot)
library(readxl)

## Setup output directory 
output <- "C:/Users/apmc/OneDrive - Norwegian University of Life Sciences/3. Follo Forest 2021-2023/Manuscripts/Analyses/Outputs"

file.name <- "CombiningManualAcousticAnalysis"

todays_date <- Sys.Date()
 
dir.name <- str_c(output,"/", file.name, "_", todays_date)
dir.name
 
output_today <- dir.name
output_today

dir.create(output_today)
output_today
#"C:/Users/apmc/OneDrive - Norwegian University of Life Sciences/3. Follo Forest 2021-2023/Manuscripts/Analyses/Outputs/CombiningManualAcousticAnalysis_2023-12-13"

# For later 
mkt <- read_csv("P:/FolloForest2021/FolloForest2022/Acoustics_Subsets/MathildeKTholme/OB/FinalManualIDOutput_MKT_24022023.csv",
     col_types = cols(...1 = col_skip()))
dim(mkt)
names(mkt)
mkt$manualid_clean <- factor(mkt$manualid_clean)
levels(mkt$manualid_clean)
table(mkt$manualid_clean)
# 19811 

```


```{r}
# folders where csv files are all in for each site
    #  / for /          

input_BARBAR <-"P:/FolloForest2021/FolloForest_ManualAcousticAnalysis/BARBAR/subset1/ID" 

input_EPTNIL <-"P:/FolloForest2021/FolloForest_ManualAcousticAnalysis/EPTNIL/ID_True"

input_EPTSER <-"P:/FolloForest2021/FolloForest_ManualAcousticAnalysis/EPTSER/ID"

input_MYOALC <-"P:/FolloForest2021/FolloForest_ManualAcousticAnalysis/MYOALC/subset1/ID"

input_MYOBEC <- "P:/FolloForest2021/FolloForest_ManualAcousticAnalysis/MYOBEC/subset1/ID"

input_MYOBRA1 <- "P:/FolloForest2021/FolloForest_ManualAcousticAnalysis/MYOBRA/subset1/ID1"
input_MYOBRA2 <- "P:/FolloForest2021/FolloForest_ManualAcousticAnalysis/MYOBRA/subset1/ID2"
input_MYOBRA3 <- "P:/FolloForest2021/FolloForest_ManualAcousticAnalysis/MYOBRA/subset1/ID3"

input_MYODAS <- "P:/FolloForest2021/FolloForest_ManualAcousticAnalysis/MYODAS/subset1/ID"

input_MYODAU1 <- "P:/FolloForest2021/FolloForest_ManualAcousticAnalysis/MYODAU/subset1/ID1"
input_MYODAU2 <- "P:/FolloForest2021/FolloForest_ManualAcousticAnalysis/MYODAU/subset1/ID2"
input_MYODAU3 <- "P:/FolloForest2021/FolloForest_ManualAcousticAnalysis/MYODAU/subset1/ID3"
input_MYODAU4 <- "P:/FolloForest2021/FolloForest_ManualAcousticAnalysis/MYODAU/subset1/ID4"

input_MYOMYO <- "P:/FolloForest2021/FolloForest_ManualAcousticAnalysis/MYOMYO/subset1/ID"

input_MYOMYS1 <- "P:/FolloForest2021/FolloForest_ManualAcousticAnalysis/MYOMYS/subset1/ID1"
input_MYOMYS2 <- "P:/FolloForest2021/FolloForest_ManualAcousticAnalysis/MYOMYS/subset1/ID2"

input_MYONAT <- "P:/FolloForest2021/FolloForest_ManualAcousticAnalysis/MYONAT/subset1/ID"

input_NoIDCB <- "P:/FolloForest2021/FolloForest_ManualAcousticAnalysis/NoID/NoIDCB/ID"
input_NoIDIB <- "P:/FolloForest2021/FolloForest_ManualAcousticAnalysis/NoID/NoIDIB/ID"
input_NoIDOB <- "P:/FolloForest2021/FolloForest_ManualAcousticAnalysis/NoID/NoIDOB/ID"

input_NYCLEI <- "P:/FolloForest2021/FolloForest_ManualAcousticAnalysis/NYCLEI/ID"

input_NYCNOC <- "P:/FolloForest2021/FolloForest_ManualAcousticAnalysis/NYCNOC/ID"

input_PIPNAT <- "P:/FolloForest2021/FolloForest_ManualAcousticAnalysis/PIPNAT/ID"

input_PIPPIP <- "P:/FolloForest2021/FolloForest_ManualAcousticAnalysis/PIPPIP/ID"

input_PIPPYG<- "P:/FolloForest2021/FolloForest_ManualAcousticAnalysis/PIPPYG/ID"

input_PLEAUR<- "P:/FolloForest2021/FolloForest_ManualAcousticAnalysis/PLEAUR/subset1/ID"

input_PLEAUS<- "P:/FolloForest2021/FolloForest_ManualAcousticAnalysis/PLEAUS/subset1/ID"

input_VESMUR<- "P:/FolloForest2021/FolloForest_ManualAcousticAnalysis/VESMUR/ID"

```

BARBAR

EPTNIL

EPTSER

MYOALC

MYOBEC

MYOBRA1
MYOBRA2
MYOBRA3

MYODAS

MYODAU1
MYODAU2
MYODAU3
MYODAU4

MYOMYO

MYOMYS1
MYOMYS2

MYONAT

NoIDCB
NoIDIB
NoIDOB

NYCLEI

NYCNOC

PIPNAT

PIPPIP

PIPPYG

PLEAUR

PLEAUS

VESMUR


```{r}
### Pull the id.csv files 
BARBAR <- list.files(path=input_BARBAR, pattern="meta.csv", recursive = TRUE)

EPTNIL <- list.files(path=input_EPTNIL, pattern="meta.csv", recursive = TRUE)
EPTNILdf <- as_tibble(EPTNIL) # remove a backup 
EPTNIL <- EPTNILdf[1,]
EPTNIL <- EPTNIL$value
# 
EPTSER <- list.files(path=input_EPTSER, pattern="meta.csv", recursive = TRUE)
# 
MYOALC <- list.files(path=input_MYOALC, pattern="meta.csv", recursive = TRUE)
# 
MYOBEC <- list.files(path=input_MYOBEC, pattern="meta.csv", recursive = TRUE)
# 
MYOBRA1 <- list.files(path=input_MYOBRA1, pattern="meta.csv", recursive = TRUE)
MYOBRA2 <- list.files(path=input_MYOBRA2, pattern="meta.csv", recursive = TRUE)
MYOBRA3 <- list.files(path=input_MYOBRA3, pattern="meta.csv", recursive = TRUE)
# 
MYODAS  <- list.files(path=input_MYODAS, pattern="meta.csv", recursive = TRUE)
# 
MYODAU1 <- list.files(path=input_MYODAU1, pattern="meta.csv", recursive = TRUE)
MYODAU2 <- list.files(path=input_MYODAU2, pattern="meta.csv", recursive = TRUE)
MYODAU3 <- list.files(path=input_MYODAU3, pattern="meta.csv", recursive = TRUE)
MYODAU4 <- list.files(path=input_MYODAU4, pattern="meta.csv", recursive = TRUE)
# 
MYOMYO <- list.files(path=input_MYOMYO, pattern="meta.csv", recursive = TRUE)
# 
MYOMYS1 <- list.files(path=input_MYOMYS1, pattern="meta.csv", recursive = TRUE)
MYOMYS2 <- list.files(path=input_MYOMYS2, pattern="meta.csv", recursive = TRUE)
# 
MYONAT <- list.files(path=input_MYONAT, pattern="meta.csv", recursive = TRUE)
# 
NoIDCB <- list.files(path=input_NoIDCB, pattern="meta.csv", recursive = TRUE)
NoIDIB <- list.files(path=input_NoIDIB, pattern="meta.csv", recursive = TRUE)
NoIDOB <- list.files(path=input_NoIDOB, pattern="meta.csv", recursive = TRUE)
# 
NYCLEI <- list.files(path=input_NYCLEI, pattern="meta.csv", recursive = TRUE)
# 
NYCNOC <- list.files(path=input_NYCNOC, pattern="meta.csv", recursive = TRUE)
# 
PIPNAT <- list.files(path=input_PIPNAT, pattern="meta.csv", recursive = TRUE)
# 
PIPPIP <- list.files(path=input_PIPPIP, pattern="meta.csv", recursive = TRUE)

PIPPYG <- list.files(path=input_PIPPYG, pattern="meta.csv", recursive = TRUE)

PLEAUR <- list.files(path=input_PLEAUR, pattern="meta.csv", recursive = TRUE)

PLEAUS <- list.files(path=input_PLEAUS, pattern="meta.csv", recursive = TRUE)

VESMUR <- list.files(path=input_VESMUR, pattern="meta.csv", recursive = TRUE)

```



```{r}

knitr::opts_chunk$set(
    root.dir = setwd(rprojroot::find_rstudio_root_file(input_BARBAR)))
getwd()

BARBAR_data <- lapply(BARBAR, read.csv)
# 
# EPTNIL 
knitr::opts_chunk$set(
    root.dir = setwd(rprojroot::find_rstudio_root_file(input_EPTNIL)))
getwd()

EPTNIL_data <- lapply(EPTNIL, read.csv)
# 
# EPTSER
knitr::opts_chunk$set(
    root.dir = setwd(rprojroot::find_rstudio_root_file(input_EPTSER)))
getwd()

EPTSER_data <- lapply(EPTSER, read.csv)
# 
# MYOALC
knitr::opts_chunk$set(
    root.dir = setwd(rprojroot::find_rstudio_root_file(input_MYOALC)))
getwd()

MYOALC_data <- lapply(MYOALC, read.csv)

# MYOBEC
knitr::opts_chunk$set(
    root.dir = setwd(rprojroot::find_rstudio_root_file(input_MYOBEC)))
getwd()

MYOBEC_data <- lapply(MYOBEC, read.csv)

# MYOBRA1
knitr::opts_chunk$set(
    root.dir = setwd(rprojroot::find_rstudio_root_file(input_MYOBRA1)))
getwd()

MYOBRA1_data <- lapply(MYOBRA1, read.csv)
# MYOBRA2
knitr::opts_chunk$set(
    root.dir = setwd(rprojroot::find_rstudio_root_file(input_MYOBRA2)))
getwd()

MYOBRA2_data <- lapply(MYOBRA2, read.csv)

# MYOBRA3
knitr::opts_chunk$set(
    root.dir = setwd(rprojroot::find_rstudio_root_file(input_MYOBRA3)))
getwd()

MYOBRA3_data <- lapply(MYOBRA3, read.csv)
# 
# MYODAS
knitr::opts_chunk$set(
    root.dir = setwd(rprojroot::find_rstudio_root_file(input_MYODAS)))
getwd()

MYODAS_data <- lapply(MYODAS, read.csv)

# MYODAU1
knitr::opts_chunk$set(
    root.dir = setwd(rprojroot::find_rstudio_root_file(input_MYODAU1)))
getwd()

MYODAU1_data <- lapply(MYODAU1, read.csv)

# MYODAU2
knitr::opts_chunk$set(
    root.dir = setwd(rprojroot::find_rstudio_root_file(input_MYODAU2)))
getwd()

MYODAU2_data <- lapply(MYODAU2, read.csv)

# MYODAU3
knitr::opts_chunk$set(
    root.dir = setwd(rprojroot::find_rstudio_root_file(input_MYODAU3)))
getwd()

MYODAU3_data <- lapply(MYODAU3, read.csv)

# MYODAU4
knitr::opts_chunk$set(
    root.dir = setwd(rprojroot::find_rstudio_root_file(input_MYODAU4)))
getwd()

MYODAU4_data <- lapply(MYODAU4, read.csv)
# 
# MYOMYO
knitr::opts_chunk$set(
    root.dir = setwd(rprojroot::find_rstudio_root_file(input_MYOMYO)))
getwd()

MYOMYO_data <- lapply(MYOMYO, read.csv)
# 
# MYOMYS1
knitr::opts_chunk$set(
    root.dir = setwd(rprojroot::find_rstudio_root_file(input_MYOMYS1)))
getwd()

MYOMYS1_data <- lapply(MYOMYS1, read.csv)

# MYOMYS2
knitr::opts_chunk$set(
    root.dir = setwd(rprojroot::find_rstudio_root_file(input_MYOMYS2)))
getwd()

MYOMYS2_data <- lapply(MYOMYS2, read.csv)

# MYONAT
knitr::opts_chunk$set(
    root.dir = setwd(rprojroot::find_rstudio_root_file(input_MYONAT)))
getwd()

MYONAT_data <- lapply(MYONAT, read.csv)
# 
# NoIDCB
knitr::opts_chunk$set(
    root.dir = setwd(rprojroot::find_rstudio_root_file(input_NoIDCB)))
getwd()

NoIDCB_data <- lapply(NoIDCB, read.csv)

# NoIDIB
knitr::opts_chunk$set(
    root.dir = setwd(rprojroot::find_rstudio_root_file(input_NoIDIB)))
getwd()

NoIDIB_data <- lapply(NoIDIB, read.csv)

# NoIDOB
knitr::opts_chunk$set(
    root.dir = setwd(rprojroot::find_rstudio_root_file(input_NoIDOB)))
getwd()

NoIDOB_data <- lapply(NoIDOB, read.csv)
# 
# NYCLEI
knitr::opts_chunk$set(
    root.dir = setwd(rprojroot::find_rstudio_root_file(input_NYCLEI)))
getwd()

NYCLEI_data <- lapply(NYCLEI, read.csv)
# 
# NYCNOC
knitr::opts_chunk$set(
    root.dir = setwd(rprojroot::find_rstudio_root_file(input_NYCNOC)))
getwd()

NYCNOC_data <- lapply(NYCNOC, read.csv)
# 
# PIPNAT
knitr::opts_chunk$set(
    root.dir = setwd(rprojroot::find_rstudio_root_file(input_PIPNAT)))
getwd()

PIPNAT_data <- lapply(PIPNAT, read.csv)
# 
# PIPPIP
knitr::opts_chunk$set(
    root.dir = setwd(rprojroot::find_rstudio_root_file(input_PIPPIP)))
getwd()

PIPPIP_data <- lapply(PIPPIP, read.csv)
# 
# PIPPYG
knitr::opts_chunk$set(
    root.dir = setwd(rprojroot::find_rstudio_root_file(input_PIPPYG)))
getwd()

PIPPYG_data <- lapply(PIPPYG, read.csv)
# 
# PLEAUR
knitr::opts_chunk$set(
    root.dir = setwd(rprojroot::find_rstudio_root_file(input_PLEAUR)))
getwd()

PLEAUR_data <- lapply(PLEAUR, read.csv)
# 
# PLEAUS
knitr::opts_chunk$set(
    root.dir = setwd(rprojroot::find_rstudio_root_file(input_PLEAUS)))
getwd()

PLEAUS_data <- lapply(PLEAUS, read.csv)
# 
# VESMUR
knitr::opts_chunk$set(
    root.dir = setwd(rprojroot::find_rstudio_root_file(input_VESMUR)))
getwd()

VESMUR_data <- lapply(VESMUR, read.csv)

```


```{r}
#To add the name of each csv in the list

#BARBAR
names(BARBAR_data) <- gsub("//.csv$", "", BARBAR)

#EPTNIL
names(EPTNIL_data) <- gsub("//.csv$", "", EPTNIL)

#EPTSER
names(EPTSER_data) <- gsub("//.csv$", "", EPTSER)

#MYOALC
names(MYOALC_data) <- gsub("//.csv$", "", MYOALC)

#MYOBEC
names(MYOBEC_data) <- gsub("//.csv$", "", MYOBEC)

#MYOBRA1
names(MYOBRA1_data) <- gsub("//.csv$", "", MYOBRA1)

#MYOBRA2
names(MYOBRA2_data) <- gsub("//.csv$", "", MYOBRA2)

#MYOBRA3
names(MYOBRA3_data) <- gsub("//.csv$", "", MYOBRA3)

#MYODAS
names(MYODAS_data) <- gsub("//.csv$", "", MYODAS)

#MYODAU1
names(MYODAU1_data) <- gsub("//.csv$", "", MYODAU1)

#MYODAU2
names(MYODAU2_data) <- gsub("//.csv$", "", MYODAU2)

#MYODAU3
names(MYODAU3_data) <- gsub("//.csv$", "", MYODAU3)

#MYODAU4
names(MYODAU4_data) <- gsub("//.csv$", "", MYODAU4)

#MYOMYO
names(MYOMYO_data) <- gsub("//.csv$", "", MYOMYO)

#MYOMYS1
names(MYOMYS1_data) <- gsub("//.csv$", "", MYOMYS1)

MYOMYS2
names(MYOMYS2_data) <- gsub("//.csv$", "", MYOMYS2)

#MYONAT
names(MYONAT_data) <- gsub("//.csv$", "", MYONAT)

#NoIDCB
names(NoIDCB_data) <- gsub("//.csv$", "", NoIDCB)

#NoIDIB
names(NoIDIB_data) <- gsub("//.csv$", "", NoIDIB)

#NoIDOB
names(NoIDOB_data) <- gsub("//.csv$", "", NoIDOB)

#NYCLEI
names(NYCLEI_data) <- gsub("//.csv$", "", NYCLEI)

#NYCNOC
names(NYCNOC_data) <- gsub("//.csv$", "", NYCNOC)

#PIPNAT
names(PIPNAT_data) <- gsub("//.csv$", "", PIPNAT)

#PIPPIP
names(PIPPIP_data) <- gsub("//.csv$", "", PIPPIP)

#PIPPYG
names(PIPPYG_data) <- gsub("//.csv$", "", PIPPYG)

#PLEAUR
names(PLEAUR_data) <- gsub("//.csv$", "", PLEAUR)

#PLEAUS
names(PLEAUS_data) <- gsub("//.csv$", "", PLEAUS)

#VESMUR
names(VESMUR_data) <- gsub("//.csv$", "", VESMUR)


#To create one single dataframe with all single dataframes
big_BARBAR <- rbindlist(BARBAR_data, fill = TRUE)

big_EPTNIL <- rbindlist(EPTNIL_data, fill = TRUE)

big_EPTSER <- rbindlist(EPTSER_data, fill = TRUE)

big_MYOALC <- rbindlist(MYOALC_data, fill = TRUE)

big_MYOBEC <- rbindlist(MYOBEC_data, fill = TRUE)

big_MYOBRA1 <- rbindlist(MYOBRA1_data, fill = TRUE)
big_MYOBRA2 <- rbindlist(MYOBRA2_data, fill = TRUE)
big_MYOBRA3 <- rbindlist(MYOBRA3_data, fill = TRUE)

big_MYODAS <- rbindlist(MYODAS_data, fill = TRUE)

big_MYODAU1 <- rbindlist(MYODAU1_data, fill = TRUE)
big_MYODAU2 <- rbindlist(MYODAU2_data, fill = TRUE)
big_MYODAU3 <- rbindlist(MYODAU3_data, fill = TRUE)
big_MYODAU4 <- rbindlist(MYODAU4_data, fill = TRUE)

big_MYOMYO <- rbindlist(MYOMYO_data, fill = TRUE)

big_MYOMYS1 <- rbindlist(MYOMYS1_data, fill = TRUE)
big_MYOMYS2 <- rbindlist(MYOMYS2_data, fill = TRUE)

big_MYONAT <- rbindlist(MYONAT_data, fill = TRUE)

big_NoIDCB <- rbindlist(NoIDCB_data, fill = TRUE)
big_NoIDIB <- rbindlist(NoIDIB_data, fill = TRUE)
big_NoIDOB <- rbindlist(NoIDOB_data, fill = TRUE)

big_NYCLEI <- rbindlist(NYCLEI_data, fill = TRUE)

big_NYCNOC <- rbindlist(NYCNOC_data, fill = TRUE)

big_PIPNAT <- rbindlist(PIPNAT_data, fill = TRUE)

big_PIPPIP<- rbindlist(PIPPIP_data, fill = TRUE)

big_PIPPYG <- rbindlist(PIPPYG_data, fill = TRUE)

big_PLEAUR <- rbindlist(PLEAUR_data, fill = TRUE)

big_PLEAUS <- rbindlist(PLEAUS_data, fill = TRUE)

big_VESMUR <- rbindlist(VESMUR_data, fill = TRUE)

alist <- list(big_BARBAR, big_EPTNIL, big_EPTSER,
              big_MYOALC, big_MYOBEC, 
              big_MYOBRA1, big_MYOBRA2, big_MYOBRA3, 
              big_MYODAS,
              big_MYODAU1, big_MYODAU2, big_MYODAU3, big_MYODAU4,
              big_MYOMYO,
              big_MYOMYS1, big_MYOMYS2,
              big_MYONAT, 
              big_NoIDCB, big_NoIDIB, big_NoIDOB, 
              big_NYCLEI, big_NYCNOC,
              big_PIPNAT, big_PIPPIP, big_PIPPYG, 
              big_PLEAUR, big_PLEAUS, big_VESMUR) 

big_data <- rbindlist(alist, fill=TRUE)
dim(big_data)
# 84874    32

# check that these are all unique files 
big_check <- as.data.frame(big_data$IN.FILE)
test <- distinct(big_check)
big_check <- big_data$IN.FILE
big_check[duplicated(big_check)]

dup <- big_data %>% filter(IN.FILE == "S4U11999_20210605_014417_000.wav")
head(dup)

# One file was copied over twice - it had the same manual ID. Remove one. 
big_data1 <- big_data %>% distinct(IN.FILE, .keep_all = TRUE)
dim(big_data1)
# 84873    32

#write.csv(big_data1, file = file.path(output_today, "allmanualacousticanalysis_2023.csv")) 
#13.12.2023
```

# Clean the manual IDs 
```{r}

# big_data1 <- read_csv("C:/Users/apmc/OneDrive - Norwegian University of Life Sciences/3. Follo Forest 2021-2023/Manuscripts/Analyses/Outputs/CombiningManualAcousticAnalysis_2023-12-13/allmanualacousticanalysis_2023.csv", 
#      col_types = cols(...1 = col_skip()))
df <- big_data1

names(df)

## some of the manual ids are under "MANUAL.ID" and the others are under "MANUAL.ID." make one column with no NAs that combines both

df1 <- df %>% dplyr::mutate(MID = dplyr::case_when(
  MANUAL.ID != "NA" ~ as.character(MANUAL.ID), 
  .default = as.character(MANUAL.ID.)))  

df1$m_id <- as.factor(df1$MID)
summary(df1$m_id)
levels(df1$m_id)
table(df1$m_id) # 

##########################################################
#### parsing multiple bats from passes ####
##########################################################

mcols <- c("manual_pass1", "manual_pass2", "manual_pass3")

df2 <- df1 %>% 
  tidyr::separate( col = m_id,
                   sep = "_", 
                   into = mcols) 

# Take passes that had 3 identical passes and make them individual rows (i.e. a pass with two bats in it is now two passes)

bat2 <- df2 %>% select(manual_pass2, IN.FILE) %>% drop_na() %>% 
  rename(manual_pass = manual_pass2) %>% mutate(manual_pass = factor(manual_pass)) # 4225 obs with 2 bats 

bat3 <- df2 %>% select(manual_pass3, IN.FILE) %>% drop_na() %>% 
  rename(manual_pass = manual_pass3) %>% mutate(manual_pass = factor(manual_pass))# 81 obs with 3 bats

# remove these colummns from df1 

df2 <- df2 %>% select(-c(manual_pass2, manual_pass3)) %>% 
               rename(manual_pass = manual_pass1) %>% mutate(manual_pass = factor(manual_pass)) # 19001 obs

df3 <- full_join(df2, bat2) #89098 obs - that adds up, good!  
df4 <- full_join(df3, bat3) #89179 obs - good! 
# 84873 + 4225 + 81 = 89179


## some of the meta data is missing for the files of second and third bat observations
# timemap <- df4 %>% select(INDIR, IN.FILE, DURATION, 
#                           DATE, TIME, HOUR, DATE.12, TIME.12, HOUR.12, 
#                           LATITUDE, LONGITUDE, MODEL, SERIAL.NO, 
#                           FIRMWARE, PREFIX, AUTO.ID, PULSES, 
#                           MATCHING, MATCH.RATIO, MARGIN) %>% distinct()
# 
# df4.5 <- left_join(df4, timemap)


# Now behavior
df5 <- df4 %>%
  mutate(manual_pass_clean = as.character(manual_pass)) %>% 
  mutate(behavior = case_when(
    str_detect(manual_pass_clean,".B.S") ~ "Both",
    str_detect(manual_pass_clean, ".S.B") ~ "Both",
    str_detect(manual_pass_clean, ".B") ~ "Feeding",
    str_detect(manual_pass_clean, ".S") ~ "Social",
    TRUE ~ "Commuting"
  )) %>% mutate(manualid = factor(manual_pass_clean), 
                behavior= factor(behavior)) %>% select(-c(manual_pass, manual_pass_clean)) %>% 
  rename(file.name = IN.FILE)
summary(df5$behavior)
     # Both Commuting   Feeding    Social 
     #  129     70359     12169      6522 

## Create a year column 
df6 <- df5 %>% mutate(year = case_when(
  str_detect(file.name, "2021") ~ "2021",
  str_detect(file.name, "2022") ~ "2022")) %>% 
  mutate(year = factor(year))  ## This was not the best solution, it had to be re-done down below:/

table(df6$year)
#  2021  2022 
# 50018 39161 

# create the site and siteplot folders 
#library(readxl)
detectors <- read_excel("C:/Users/apmc/OneDrive - Norwegian University of Life Sciences/3. Follo Forest 2021-2023/Manuscripts/Analyses/Inputs/detector_overview_2021_2022 - Copy.xlsx")

names(detectors)
# "Site ID"  "Detector" "year"

# some detectors do not have the serial name, they have an old project name instead
fix <- df %>% dplyr::filter(grepl("VEMU", IN.FILE)) 
fix$SERIAL.NO <- factor(fix$SERIAL.NO)
levels(fix$SERIAL.NO)
#"S4U10137"

df6. <- df6 
df6.$fix.file <- gsub("VEMUROOFTOP", "S4U10137", df6.$file.name)

df6 <- df6. %>% dplyr::mutate(Detector =substr(fix.file, 1,8)) 

df6$detector.year <- paste0(df6$Detector, "_", df6$year)

## There is some missing data but I can only address some of it for now 

detectors$detector.year <- paste0(detectors$Detector, "_", detectors$year)

detectors1 <- detectors %>% select(c(`Site ID`, detector.year))

df7 <- left_join(df6, detectors1)


df7$SiteID <- df7$`Site ID`

df8 <- df7 %>% mutate(SitePlot = SiteID) %>% 
  mutate(PlotType = case_when(
  str_detect(SitePlot, "-OB") ~ "Open",
  str_detect(SitePlot, "-CB") ~ "Canopy", 
  str_detect(SitePlot, "-IB") ~ "Interior")) %>% 
  mutate(SitePlot = factor(SitePlot))

df9 <- df8 %>% select(c(INDIR, file.name, DATE, TIME, HOUR,
                         DATE.12, TIME.12, HOUR.12, AUTO.ID, 
                         MATCH.RATIO, manualid, behavior, SitePlot, PlotType, year))




## Now add in mkt data 
mkt1 <- mkt %>% select(c(INDIR, file.name, DATE, TIME, HOUR,
                         DATE.12, TIME.12, HOUR.12, AUTO.ID, 
                         MATCH.RATIO, manualid_clean, behavior, 
                         SitePlot, PlotType)) %>% 
  rename(manualid = manualid_clean) %>% ungroup()

mkt1$year <- "2022"
mkt1$year <- as.factor(mkt1$year)
mkt1$PlotType <- as.factor(mkt1$PlotType)
summary(mkt1)


df9$DATE <- as.Date(df9$DATE)
df9$DATE.12 <- as.Date(df9$DATE.12)
mkt1$TIME <- as.character(mkt1$TIME)
mkt1$TIME.12 <- as.character(mkt1$TIME.12)

dim(mkt1) # 19811    15
dim(df9) # 89179    15
# 89179 + 19811 = 108990 - good! 

df10 <- full_join(df9, mkt1) 
dim(df10)
#108990     15


## Check for duplicates
mktest <- mkt1 %>% select(file.name) %>% distinct()
dftest <- df9 %>% select(file.name) %>% distinct() 

test <- inner_join(mktest, dftest)
# 1 S4U11994_20220630_022005_000.wav

dup <- df9 %>% filter(file.name == "S4U11994_20220630_022005_000.wav")
dup1 <- mkt %>% filter(file.name == "S4U11994_20220630_022005_000.wav") # one duplicate that should be removed. 
# the manual ID is in agreement 

addthis <- df9 %>% filter(file.name == "S4U11994_20220630_022005_000.wav")

df11 <- df10 %>% subset(file.name !=  "S4U11994_20220630_022005_000.wav")
df12 <- full_join(df11, addthis)
dim(df12)
# 108989     15

```

# Clean the manual IDs
```{r}

df12$manualid <- factor(df12$manualid)
levels(df12$manualid)

#  [1] "EPNI"      "EPNI.B"    "EPNI.B "   "EPNI.B.S"  "EPNI.S"    "LR"        "LR1"       "LR1.B"     "LR1.S"    
# [10] "LR2"       "LR2.B"     "MR1"       "MR1 "      "MR1.B"     "MR1.S"     "MYOT"      "MYOT.B"    "MYOT.B.S" 
# [19] "MYOT.B.S." "MYOT.S"    "NYNO"      "NYNO.B"    "NoID"      "NoID*BABA" "NoID.B"    "NoID.S"    "Noise"    
# [28] "PAUR"      "PINA"      "PIPY"      "PIPY.B"    "PIPY.B.S"  "PIPY.S"    "PLAU"      "PLAU.S"    "Shrew?"   
# [37] "VEMU"      "VEMU.S"    "FMsp"      "NoID?" 

df12$behavior <- factor(df12$behavior)
summary(df12$behavior) # No NAs, good 
     # Both Commuting   Feeding    Social 
     #  148     85615     15342      7884

DF <- df12

DF$m1 <- gsub("NoID?", "NoID", DF$manualid, fixed = TRUE)
DF$m2 <- gsub("Shrew?", "Noise", DF$m1, fixed = TRUE)
DF$m3 <- gsub(".B", "", DF$m2)
DF$m4 <- gsub(".S.", "", DF$m3)
DF$m5 <- gsub(".S", "", DF$m4)
DF$m6 <- gsub("EPNI ", "EPNI", DF$m5)
DF$m7 <- gsub("FMsp", "MYOT", DF$m6)
DF$m8 <- gsub("LR", "LR2", DF$m7)
DF$m9 <- gsub("NoIDA", "NoID", DF$m8)
DF$m10 <- gsub("MR1 ", "MR1", DF$m9)
DF$m11 <- gsub("LR21", "LR1", DF$m10)
DF$m12 <- gsub("LR22", "LR2", DF$m11)
DF$m13 <- gsub("VEMU", "LR2", DF$m12)
DF$m14 <- gsub("PLAU", "PAUR", DF$m13)

DF$m14 <- factor(DF$m14)
 levels(DF$m14)
 # [1] "EPNI"  "LR1"   "LR2"   "MR1"   "MYOT"  "NYNO"  "NoID"  "Noise"
 # [9] "PAUR"  "PINA"  "PIPY" 

DF$manual.id <- DF$m14

DF1 <- DF %>% select(INDIR, file.name, 
                     DATE, TIME, HOUR, 
                     DATE.12, TIME.12, HOUR.12,
                     AUTO.ID, MATCH.RATIO, 
                     manual.id, behavior, 
                     SitePlot, PlotType, year) %>% 
  mutate(guild = case_when(
    manual.id %in% c("MYOT", "PAUR", "PLAU") ~ "SRE",
    manual.id %in% c("MR1", "PINA", "PIPY") ~ "MRE", 
    manual.id %in% c("LR1", "LR2", "EPNI", "NYNO") ~ "LRE",
    manual.id == "NoID" ~ "NoID", 
    manual.id == "Noise" ~ "Noise"
  )) %>% 
  mutate(SitePlotYear = paste0(SitePlot, "-", year)) %>% 
  mutate(across(c(manual.id, behavior, SitePlot, PlotType, year, SitePlotYear), factor)) 

summary(DF1)


dim(DF1)
# 108989     16

DF1$SitePlot <- factor(DF1$SitePlot)
summary(DF1$SitePlotYear)

## Fix the date time hour issue 

timefix <- DF1 %>% 
  select(file.name, DATE, TIME, HOUR, DATE.12, TIME.12, HOUR.12, AUTO.ID, MATCH.RATIO, INDIR) %>% 
  distinct()

DFna <- DF1 %>% filter(!complete.cases(DATE)) #5116 obs that are missing datetime 
names(DFna)
DFna1 <- DFna %>% select(file.name, SitePlot, PlotType, year, SitePlotYear) %>% distinct()
na_filenames <- DFna1$file.name

timefix1 <- timefix %>% 
  filter(file.name %in% na_filenames) %>%
  filter(complete.cases(file.name, DATE, TIME, HOUR, DATE.12, TIME.12, HOUR.12, AUTO.ID, INDIR))
  

DFfix <- merge(DFna1, timefix1, by = "file.name", all.x = TRUE) %>% 
  select(file.name, DATE, TIME, HOUR, DATE.12, TIME.12, HOUR.12)

DF1$uid <- paste0("UID", 1:nrow(DF1))

DF2 <- left_join(DF1, DFfix, by = "file.name") # NEARLY fixed

names(DF2)

DF2$DATE.x <- as.character(DF2$DATE.x)
DF2$DATE.y <- as.character(DF2$DATE.y)
DF2$DATE.12.x <- as.character(DF2$DATE.12.x)
DF2$DATE.12.y <- as.character(DF2$DATE.12.y)

DF2$TIME.x <- as.character(DF2$TIME.x)
DF2$TIME.y <- as.character(DF2$TIME.y)
DF2$TIME.12.x <- as.character(DF2$TIME.12.x)
DF2$TIME.12.y <- as.character(DF2$TIME.12.y)

DF2$HOUR.x <- as.character(DF2$HOUR.x)
DF2$HOUR.y <- as.character(DF2$HOUR.y)
DF2$HOUR.12.x <- as.character(DF2$HOUR.12.x)
DF2$HOUR.12.y <- as.character(DF2$HOUR.12.y)

DF3 <- DF2 %>% 
  mutate(DATE = as.Date(case_when(
  is.na(DATE.x) ~ DATE.y, 
  DATE.x != "NA" ~ DATE.x))) %>% 
    
  mutate(TIME = case_when( 
  is.na(TIME.x) ~ TIME.y, 
  TIME.x != "NA" ~ TIME.x)) %>% 
  
  mutate(HOUR = as.integer(case_when(
  is.na(HOUR.x) ~ HOUR.y, 
  HOUR.x != "NA" ~ HOUR.x))) %>% 
  
  mutate(DATE.12 = as.Date(case_when(
  is.na(DATE.12.x) ~ DATE.12.y, 
  DATE.12.x != "NA" ~ DATE.12.x))) %>% 
    
  mutate(TIME.12 = case_when( 
  is.na(TIME.12.x) ~ TIME.12.y, 
  TIME.12.x != "NA" ~ TIME.12.x)) %>% 
  
  mutate(HOUR.12 = as.integer(case_when(
  is.na(HOUR.12.x) ~ HOUR.12.y, 
  HOUR.12.x != "NA" ~ HOUR.12.x))) %>% 
  
  select(-c(DATE.x, DATE.y, TIME.x, TIME.y, HOUR.x, HOUR.y,
            DATE.12.x, DATE.12.y, TIME.12.x, TIME.12.y, HOUR.12.x, HOUR.12.y)) %>% 
  
  mutate(datetime = as.POSIXct(paste0(DATE, " ", TIME), format = "%Y-%m-%d %H:%M:%OS", 
                               tz = "Europe/Berlin")) %>% 
  mutate(nighttime = as.POSIXct(paste0(DATE.12, " ", TIME.12), format = "%Y-%m-%d %H:%M:%OS", 
                               tz = "Europe/Berlin")) %>% 
  mutate(guild = factor(guild)) 


#write.csv(DF3, file = file.path(output_today, "ManualAnalaysis21_22_combined_datetime_fixed_troubleshooting_gaps.csv"))

# 15.12.2023

```


## Compare with the AUTO.IDs - check for subsetting errors and gaps in the data 
```{r}

FF <- read_csv("C:/Users/apmc/OneDrive - Norwegian University of Life Sciences/3. Follo Forest 2021-2023/Manuscripts/Analyses/Outputs/SummarizingBatAcousticData_2023-10-12/Simple_AllBatData.CSV",
     col_types = cols(...1 = col_skip()))
dim(FF)
# [1] 416936     17

## Format columns:
aFF <- FF %>% 
  rename(PlotType = Plot) %>% 
  mutate(Site = factor(Site), 
   SitePlot = factor(SitePlot),
   PlotType = factor(PlotType), 
   Collection = factor(Collection),
   year = factor(year), 
   autoid = factor(autoid)) %>%## Create a MYTO autoid for easier comparison 
 mutate(auto.id = case_when(
        autoid %in% c("MYOALC", "MYOBEC", "MYOBRA", 
               "MYODAS", "MYODAU", "MYOMYO", "MYOMYS", "MYONAT") ~ "MYOT",
                        .default = autoid)) %>% 
                      mutate(auto.id = factor(auto.id)) %>% 
                      mutate(guild = case_when(
                      auto.id %in% c("BARBAR", "MYOT", "PLEAUR", "PLEAUS") ~ "SRE", 
                      auto.id %in% c("PIPPIP", "PIPNAT", "PIPPYG") ~ "MRE",
                      auto.id %in% c("NYCNOC", "NYCLEI", "EPTNIL", "EPTSER", "VESMUR") ~ "LRE",
                      auto.id == "NoID" ~ "NoID")) %>% 
  mutate(guild = factor(guild)) 

levels(aFF$auto.id)
levels(aFF$guild)

aFF$year <- as.factor(year(aFF$DATE))  

aFF21 <- aFF %>% filter(year == 2021 & auto.id != "Noise") %>% droplevels() # 222521     17
aFF22 <- aFF %>% filter(year == 2022 & auto.id != "Noise") %>% droplevels() # 194415     17

################################################################################
# Manual acoustic analysis results 

## Make an experimental categorical variable for different times in the summer


### Fix the SitePlot Issues 

DF4 <- DF3 %>% 
  select(-c(SitePlotYear, SitePlot, PlotType, year)) %>%
  mutate(year = as.factor(year(DF3$DATE))) 

DF4$fix.file <- gsub("VEMUROOFTOP", "S4U10137", DF4$file.name)

DF4.5 <- DF4 %>% dplyr::mutate(Detector =substr(fix.file, 1,8)) 

DF4.5$detector.year <- paste0(DF4.5$Detector, "_", DF4.5$year)
  
detectors2 <- detectors1 %>% rename(SitePlot = "Site ID")  

DF4.6 <- left_join(DF4.5, detectors2)

DF4.7 <- DF4.6   %>%  mutate(PlotType = case_when(
  str_detect(SitePlot, "-OB") ~ "Open",
  str_detect(SitePlot, "-CB") ~ "Canopy", 
  str_detect(SitePlot, "-IB") ~ "Interior")) %>% 
  mutate(SitePlot = factor(SitePlot)) %>% 
  mutate(Site = factor(substr(SitePlot, 1,4))) 

mFF <- DF4.7
table(mFF$Site)

mFF$year <- as.factor(year(mFF$DATE)) 
mFF21 <- mFF %>% filter(year == 2021) %>% filter(manual.id != "Noise") %>% droplevels() # 48866 obs
mFF22 <- mFF %>% filter(year == 2022) %>% filter(manual.id != "Noise") %>% droplevels() # 57659 obs 

summary(mFF21$DATE)
summary(mFF22$DATE)
## How many passes belong to MYOT and 2022?

################################################################################
# Compare temporal coverage of autoids/manualids 

## 2021

a <- ggplot(mFF21) + geom_point(aes(x = DATE), stat = "count") + 
  facet_wrap(~guild) + theme_minimal() + 
  ggtitle("Manual acoustic analysis") + 
  xlab("2021")
a

b <- ggplot(aFF21) + geom_point(aes(x = DATE), stat = "count") + 
  facet_wrap(~guild) + theme_minimal() + 
  ggtitle("Automaitc acoustic analysis") + 
  xlab("2021")

plot_grid(a,b)


## 2022 

a <- ggplot(mFF22) + geom_point(aes(x = DATE), stat = "count") + 
  facet_wrap(~guild) + theme_minimal() + 
  ggtitle("Manual acoustic analysis") + 
  xlab("2022")

b <- ggplot(aFF22) + geom_point(aes(x = DATE), stat = "count") + 
  facet_wrap(~guild) + theme_minimal() + 
  ggtitle("Automaitc acoustic analysis") + 
  xlab("2022")

plot_grid(a,b)

### SRE bats only 


a <- ggplot(mFF21  %>% filter(guild == "SRE") %>% droplevels()) + 
  geom_point(aes(x = DATE), stat = "count", color = "gray", alpha = 0.7) + 
  geom_smooth(aes(x = DATE, color = PlotType, fill = PlotType), stat = "count") + 
  theme_minimal() + 
  ggtitle("") + 
  xlab("2021") + theme(legend.position = "none") + ggtitle("Manual acoustic analysis - SRE bats only")


b <- ggplot(mFF22  %>% filter(guild == "SRE") %>% droplevels()) + 
  geom_point(aes(x = DATE), stat = "count", color = "gray", alpha = 0.7) + 
  geom_smooth(aes(x = DATE, color = PlotType, fill = PlotType), stat = "count") + 
  theme_minimal() + 
  ggtitle("") + 
  xlab("2022") + theme(legend.position = "none") 

plot_grid(a,b, nrow = 2) 


#### Where are the gaps in monitoring? 
## Auto 
a <- ggplot(aFF21) + geom_count(aes(x = DATE, y=Site), alpha = 0.5) + 
  facet_wrap(~PlotType, nrow=3) + theme_minimal() + 
  ggtitle("Automaitc acoustic analysis") + 
  xlab("2021") + theme(legend.position = "none")


b <- ggplot(aFF22) + geom_count(aes(x = DATE, y=Site), alpha = 0.5) + 
  facet_wrap(~PlotType, nrow=3) + theme_minimal() + 
  ggtitle("Automaitc acoustic analysis") + 
  xlab("2022") + theme(legend.position = "none")

plot_grid(a,b)

## Manual 
a <- ggplot(mFF21) + geom_count(aes(x = DATE, y=Site), alpha = 0.5) + 
  facet_wrap(~PlotType, nrow=3) + theme_minimal() + 
  ggtitle("Manual acoustic analysis") + 
  xlab("2021") + theme(legend.position = "none")


b <- ggplot(mFF22) + geom_count(aes(x = DATE, y=Site), alpha = 0.5) + 
  facet_wrap(~PlotType, nrow=3) + theme_minimal() + 
  ggtitle("Manual acoustic analysis") + 
  xlab("2022") + theme(legend.position = "none")

plot_grid(a,b)


## Manual - SRE bats only
a <- ggplot(mFF21 %>% filter(guild == "SRE")) + geom_count(aes(x = DATE, y=Site), alpha = 0.5) + 
  facet_wrap(~PlotType, nrow=3) + theme_minimal() + 
  ggtitle("Manual acoustic analysis - SRE bats only") + 
  xlab("2021") + theme(legend.position = "none")


b <- ggplot(mFF22 %>% filter(guild == "SRE")) + geom_count(aes(x = DATE, y=Site), alpha = 0.5) + 
  facet_wrap(~PlotType, nrow=3) + theme_minimal() + 
  ggtitle("Manual acoustic analysis - SRE bats only") + 
  xlab("2022") + theme(legend.position = "none")

plot_grid(a,b)

## Manual - SRE bats and open plots only
a <- ggplot(mFF21 %>% filter(guild == "SRE" & PlotType == "Open") %>% droplevels()) + 
  geom_count(aes(x = DATE, y=Site), alpha = 0.5) + 
  facet_wrap(~PlotType, nrow=3) + theme_minimal() + 
  ggtitle("Manual acoustic analysis - SRE bats only") + 
  xlab("2021") + theme(legend.position = "none")


b <- ggplot(mFF22 %>% filter(guild == "SRE" & PlotType == "Open") %>% droplevels()) + 
  geom_count(aes(x = DATE, y=Site), alpha = 0.5) + 
  facet_wrap(~PlotType, nrow=3) + theme_minimal() + 
  ggtitle("Manual acoustic analysis - SRE bats only") + 
  xlab("2022") + theme(legend.position = "none")

plot_grid(a,b)


################################################################################

ggplot(mFF22) + geom_bar(aes(x = PlotType, fill = PlotType), stat = "count") + 
  facet_wrap(~manual.id) + theme_minimal() + 
  ggtitle("Manual acoustic analysis") + 
  xlab("2022")

ggplot(aFF22) + geom_bar(aes(x = Plot, fill = Plot), stat = "count") + 
  facet_wrap(~auto.id) + 
  theme_minimal() + 
  ggtitle("Automaitc acoustic analysis") + 
  xlab("2022")

################################################################################
# How do SRE bats use the different plots between years? Proportion bar charts 

ggplot(data = mFF21 %>% filter(guild == "SRE") %>% droplevels(), aes(x = PlotType)) + 
  geom_bar(aes(fill = behavior)) + theme_minimal() + ggtitle("Manual acoustic analysis - 2021")

ggplot(data = mFF22 %>% filter(guild == "SRE") %>% droplevels(), aes(x = PlotType)) + 
  geom_bar(aes(fill = behavior)) + theme_minimal() + ggtitle("Manual acoustic analysis - 2022")

## Now separated by month 
mFF21$month <- month(mFF21$DATE)
mFF22$month <- month(mFF22$DATE)

a <- ggplot(data = 
         mFF21 %>% 
         filter(guild == "SRE") %>% 
         filter(behavior %in% c("Feeding", "Commuting")) %>% droplevels(), 
                aes(x = PlotType)) + 
  geom_bar(aes(fill = behavior)) + 
  theme_minimal() + theme(legend.position = "none") + 
  ggtitle("Manual acoustic analysis - 2021 - SRE only - red = commuting, blue = feeding") +
  facet_wrap(~month, nrow= 1, ncol = 5) 

b <- ggplot(data = 
         mFF22 %>% 
         filter(guild == "SRE") %>%
         filter(behavior %in% c("Feeding", "Commuting")) %>% droplevels(), 
       aes(x = PlotType)) + 
  geom_bar(aes(fill = behavior)) + 
  theme_minimal() + theme(legend.position = "none") +
  ggtitle("Manual acoustic analysis - 2022 - SRE only") +
  facet_wrap(~month, nrow= 1, ncol = 5) 

plot_grid(a,b, nrow = 2)
## 

### How much does this relationship change if we break up the summer into 3 different sections? 

## Discuss different ways of sub-setting the data with Katrine 

###########################################







# 
# ggplot(batsf) + 
#   geom_bar(aes(x = AUTO.ID., fill= AUTO.ID.), stat = "count") + 
#   dark_mode() + ylab("") + xlab("") + theme(text = element_text(size = 20)) +
#   ggtitle("Overview of activity across autoids") + 
#   facet_wrap(~sitetype, nrow = 2) 
# 
# ggplot(batsf) + 
#   geom_bar(aes(x = site), stat = "count", fill = "turquoise", alpha = 0.5) + 
#   dark_mode() + ylab("") + xlab("") + theme(text = element_text(size = 20)) +
#   ggtitle("Overview of bat passes between sites") + 
#   facet_wrap(~sitetype, nrow = 2) 
# 
# ggplot(batsf) + 
#   geom_bar(aes(x = site, fill = sitetype), stat = "count", alpha = 0.5, position = "dodge") + 
#   scale_colour_manual(values = c("turquoise", "coral")) +
#   dark_mode() + ylab("") + xlab("") + theme(text = element_text(size = 20)) +
#   ggtitle("Overview of bat passes between sites") + labs(fill = "Site type")
# 
# 
# ## Remove NoID and see what it looks like 
# 
# nbatsf <- batsf %>% filter(AUTO.ID. != "NoID") %>% droplevels()
# colourCount = length(unique(nbatsf$AUTO.ID.))
# getPalette = colorRampPalette(brewer.pal(9, "BrBG"))
# 
# 
# ggplot(nbatsf) + 
#   geom_bar(aes(x = AUTO.ID.), stat = "count", fill=getPalette(colourCount)) + 
#   dark_mode() + ylab("") + xlab("") + theme(text = element_text(size = 20)) +
#   ggtitle("Overview of activity across autoids")

```
